# Generated by Django 4.0.5 on 2022-06-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0002_blogpotsllist_created_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogpotslList',
            new_name='BlogpostList',
        ),
    ]
